// Module included in the following assemblies:
//
//docs/release_notes-7.2.0/master.adoc

:_template-generated: 2024-12-04
:_mod-docs-content-type: REFERENCE

[id="resolved-issues-7-2-2_{context}"]
= Resolved issues

This section provides highlighted issues that have been resolved in {ProductFullName} 7.2.2.

.Go targets are displayed in the `Application Analysis` wizard
Previously, in the `Application Analysis` tab of {ProductShortName} GUI, the custom Go target that was selected got replaced with Java target when users revisit the `Set Target` page. This issue has been resolved in {ProductShortName} 7.2.2. link:https://issues.redhat.com/browse/MTA-3438[(MTA-3438)]

.MTA generates dependencies list from POM files within web archive files
Previously, when analyzing applications with WAR files that contained a POM file, {ProductShortName} CLI failed the analysis because no dependency was found. This issue has been resolved in {ProductShortName} 7.2.2. link:https://issues.redhat.com/browse/MTA-3415[(MTA-3415)]

.Enable or disable imported questionnaires to assess applications
Previously, when you enabled or disabled the legacy questionnaire after importing a second questionnaire, the toggle action was applied on the imported questionnaire instead of the legacy questionnaire. This issue has been resolved in {ProductShortName} 7.2.2. link: https://issues.redhat.com/browse/MTA-4630[(MTA-4630)]

For a complete list of all resolved issues, see the list of link:https://issues.redhat.com/issues/?filter=12455743[{ProductShortName} 7.2.2 resolved issues] in Jira.

