---
name: Linting with Vale on pull request

on: [pull_request]

jobs:
  vale:
    name: Linting with Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor      
      - uses: errata-ai/vale-action@v2.1.1
        with:
          version: 2.17.0
          files: docs/*
          vale_flags: "--no-exit --minAlertLevel=error"
          reporter: github-pr-review
          fail_on_error: true       
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
