---
name: Linting with Vale on pull request

on: [pull_request]

  vale:
    name: Linting with Vale
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Vale Linter
        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: false
          vale_flags: "--no-exit --config=.vale.ini"
          filter_mode: diff_context
          files: docs/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
