name: reviewdog
on:
  pull_request:

jobs:
  reviewdog-github-check:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: reviewdog (github-check)
    runs-on: ubuntu-latest
    steps:
       - name: Run reviewdog
          env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            golint ./... | reviewdog -f=golint -reporter=github-pr-check
