# This is a basic workflow to help you get started with Actions

name: Docs-Linting

on: 
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/vale.yml'      

jobs:
  vale:
    name: Linting with Vale
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor
      - uses: errata-ai/vale-action@reviewdog
        with:
          filter_mode: diff_context
          vale_flags: "--no-exit --minAlertLevel=error --glob=*.adoc"
          reporter: github-pr-review
          fail_on_error: true
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REVIEWDOG_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}